# Validate Terraform Templates
name: Validate Terraform Templates

on:
  pull_request:

jobs:
  validate-terraform-templates:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Validate Terraform templates
        run: | 
         terraform init
         terraform validate
